### PR TITLE
Primitive types

### PR DESCRIPTION
**Pull request by estebistec**
Add primitive types accepting values of any simple or compound primitive JSON type.

### CODE REVIEW

**Comment by tatiana** [comment]
@j2labs: I was searching for the AbstractType in schematics, but I couldn't find it nor in 1.0.3, nor in the develop branch. Is there some other way to achieve this behavior?

**Comment by jmsdnns** [comment]
I am not sure. I haven't maintained Schematics for a little while. Perhaps @kracekumar can advise?

**Comment by jmsdnns** [comment]
I used to go by @j2labs but I go by @jmsdnns instead now. I also do'nt hack Python anymore and only work on Objective-C or Swift. :(

**Comment by tatiana** [comment]
No problems, @jmsdnns :) Thanks a lot for the quick response!

BTW: I'm using `BaseType` and apparently it works in the expected way.

**Pull request closed without merging**
