### PR TITLE
Allow ModelOptions to have extra parameters

### LINKED ISSUE #397: ModelOptions should allow anykind of extra parameters
Got a `TypeError: __init__() got an unexpected keyword argument 'route'` error while trying to extend the Options class from my schematics model.

``` python
class Search(Model):
    uuid = UUIDType(required=True)
    revision = NumberType(required=True)
    created_at = DateTimeType(default=datetime.datetime.now)
    updated_at = DateTimeType(default=datetime.datetime.now)

    class Options:
        route = 'my_flask_route_name'
        namespace = 'searches'
        roles = {}
```

I guess that I can start my own implementation of `ModelOptions` and alter my `__optionsclass__` but that sucks.
Could you please allow an `extra` field that allow us to put all kind of stuff in the model Options ?

### PR DESCRIPTION
**Pull request by rmb938**
Closes #397 

ModelOptions can now have extra parameters. This only applies to params that start with '_'

Usage:

``` python
>>> class Foo(Model):
...     class Options:
...         _test = 123
... 
>>> Foo.Options._test
123
>>> Foo._options._test
123
```

### CODE REVIEW

**Comment by rmb938** [comment]
@bintoro Can I get some feedback on this and possibly get it merged & released?

**Comment by lkraider** [comment]
You already can set your own options class (just inherit from ~~`ModelOptions`~~ `SchemaOptions`):

```python
class FooOptions(SchemaOptions):
    def __init__(self, test=None, **kwargs):
        super(FooOptions, self).__init__(**kwargs)
        self.test = test

class Foo(Model):
    __optionsclass__ = FooOptions
    class Options:
        test = 123
```

**Comment by lkraider** [comment]
Thanks for the PR, let me know if somehow your use case is not catered by the custom class.

**Comment by lkraider** [comment]
Thanks, this has been merged now.

**Pull request closed without merging**
