### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by kracekumar**
Pull request to release 1.0.1 version to PyPI. @j2labs Can you merge this and push to PyPI ?

### CODE REVIEW

**Comment by j2labs** [comment]
Will do this today!

On Sun, Feb 1, 2015 at 1:35 PM, Kracekumar Ramaraju <
notifications@github.com> wrote:

> Pull request to release 1.0.1 version to PyPI. @j2labs
> <https://github.com/j2labs> Can you merge this and push to PyPI ?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/schematics/schematics/pull/275
> Commit Summary
>
>    - Update HISTORY.rst
>    - Update __init__.py
>
> File Changes
>
>    - *M* HISTORY.rst
>    <https://github.com/schematics/schematics/pull/275/files#diff-0> (6)
>    - *M* schematics/__init__.py
>    <https://github.com/schematics/schematics/pull/275/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/schematics/schematics/pull/275.patch
>    - https://github.com/schematics/schematics/pull/275.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/275>.
>



-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by tony** [comment]
@schematics, @j2labs : Can you follow (PEP 0440)[http://legacy.python.org/dev/peps/pep-0440/] for versioning scheme?  I think instead of ``0.5, 0.6, 0.9-0, 0.9-1, 0.9-2, 0.9-3, 0.9-4, 0.9-5, 1.0-0`` you would want ``0.5, 0.6, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 1.0.0``, this could be ``1.0.1``.

#273 mentions this already. Adhering to the standard affects things like ``distutils.version`` (https://hg.python.org/cpython/file/c3abdf016b18/Lib/distutils/version.py), pypi, pip, people in general would be happier to see standards followed going forward if possible. Why not re-release 1.0-1 as 1.0.0 too? That way going forward after 1.0 the standard is followed.

**Comment by jmsdnns** [comment]
I didnt get it out before leaving on a retreat with VHX (where i work)

I can ship wednesday at the soonest. Apologies!

On Sunday, February 1, 2015, The Ghost Of J2 Labs <notifications@github.com>
wrote:

> Will do this today!
>
> On Sun, Feb 1, 2015 at 1:35 PM, Kracekumar Ramaraju <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Pull request to release 1.0.1 version to PyPI. @j2labs
> > <https://github.com/j2labs> Can you merge this and push to PyPI ?
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/schematics/schematics/pull/275
> > Commit Summary
> >
> > - Update HISTORY.rst
> > - Update __init__.py
> >
> > File Changes
> >
> > - *M* HISTORY.rst
> > <https://github.com/schematics/schematics/pull/275/files#diff-0> (6)
> > - *M* schematics/__init__.py
> > <https://github.com/schematics/schematics/pull/275/files#diff-1> (2)
> >
> > Patch Links:
> >
> > - https://github.com/schematics/schematics/pull/275.patch
> > - https://github.com/schematics/schematics/pull/275.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/schematics/schematics/pull/275>.
> >
>
>
>
> --
> jms dnns
> jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/275#issuecomment-72385323>.
>


-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by kracekumar** [comment]
@tony Will you be happy to volunteer to come up with a process to automate this ? 

Now manually we  send a pull request for every release. We can have [invoke](http://invoke.readthedocs.org/en/latest/) command which can update version number in a certain format, create a git tag and finally to publish to PyPI which @j2labs can use.

**Comment by jmsdnns** [comment]
Krace - what is your username on pypi? I would prefer to hand over the keys
to Schematics and back away from its development if possible. I just don't
code python anymore.

On Tue, Feb 3, 2015 at 2:54 AM, Kracekumar Ramaraju <
notifications@github.com> wrote:

> @tony <https://github.com/tony> Will you be happy to volunteer to come up
> with a process to automate this ?
>
> Now manually we send a pull request for every release. We can have invoke
> <http://invoke.readthedocs.org/en/latest/> command which can update
> version number in a certain format, create a git tag and finally to publish
> to PyPI which @j2labs <https://github.com/j2labs> can use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/275#issuecomment-72608703>.
>



-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by kracekumar** [comment]
@jmsdnns Username is 	`kracekumar`.

**Comment by jmsdnns** [comment]
Done! All yours, friend!

On Wed, Feb 11, 2015 at 11:14 AM, Kracekumar Ramaraju <
notifications@github.com> wrote:

> @jmsdnns <https://github.com/jmsdnns> Username is kracekumar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/275#issuecomment-73909127>.
>



-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by kracekumar** [comment]
Awesome. Done https://pypi.python.org/pypi/schematics/1.0-1

**Pull request merged**
