### PR TITLE
Benchmark tests

### PR DESCRIPTION
**Pull request by lkraider**
This branch adds multiple benchmarks tools that can be used to test the performance of Schematics.

The following tools are used:
 - [pytest-benchmark](https://pytest-benchmark.readthedocs.org)
 - [vmprof](https://vmprof.readthedocs.org)
 - [cProfile](https://docs.python.org/2/library/profile.html#module-cProfile)
 - [airspeed velocity](https://asv.readthedocs.org)

To run the tests using `tox`:
```
tox -e benchmark
```
This will run pytest-benchmark and compare it to a baseline benchmark (saved from my machine, so results will be inconsistent), it will generate some SVG histograms on the project folder. You can run the tests multiple times while checking out revisions in git, and the histograms will be updated with all runs, allowing to compare outputs.
screen shot 2016-02-17 at 19 48 08

Vmprof will also run and upload data to their online viewer. Examples:
http://vmprof.com/#/0a0e3965f9eb8c0f89efcf67095e6960
http://vmprof.com/#/ed6458cf55dcc3b0bfc69566f53db5e6

Finally, the output of cProfile is also printed.

Tox will not run airspeed velocity, to do that install the tool in your virtualenv and run the script:
```
pip install asv
sh benchmarks/run.sh
```
This tool allows to compare performance both in time and memory across multiple commits. Example:
screen shot 2016-02-17 at 19 46 22

I added just some basic test functions, would be great to review and expand them. Also, maybe see if it's worth to add some regression tests for Travis to run on PRs.

### CODE REVIEW

**Comment by lkraider** [comment]
Note: vmprof from pypi has a bug on the upload routine, I already reported it at https://github.com/vmprof/vmprof-python/issues/43 but it's just a matter of manually editing the `upload.py` for now.

**Comment by j2labs** [comment]
RAD

On Wed, Feb 17, 2016 at 5:08 PM, Paul Eipper <notifications@github.com>
wrote:

> Note: vmprof from pypi has a bug on the upload routine, I already reported
> it at vmprof/vmprof-python#43
> <https://github.com/vmprof/vmprof-python/issues/43> but it's just a
> matter of manually editing the upload.py for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/392#issuecomment-185429433>
> .
>



-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>

**Comment by lkraider** [comment]
Note2: running these tests I was able to identify that Schematics uses more memory on initialization now (from 10mb to 16mb) with the introduction of the `net.py` types. It seems the compiled regex also add some overhead on initialization time.

**Comment by bintoro** [comment]
Yes this is most rad :rocket:

I will look at this more closely soon-ish and put together a few testcases.

**Comment by lkraider** [comment]
I am moving the asv benchmarks into a separate repo, that's their recommended usage, and also it allows to have a github page setup to publish the output.

I'll keep this PR open for now until the separate repo is setup.

**Comment by lkraider** [comment]
For reference, numba uses a separate repo for benchmarks:
https://github.com/numba/numba-benchmark

While pandas does it from the main repo:
https://github.com/pydata/pandas
http://pandas.pydata.org/pandas-docs/stable/contributing.html#running-the-performance-test-suite

**Comment by lkraider** [comment]
Repo is up:
https://github.com/schematics/schematics-benchmark

Benchmarks generated on an AWS EC2 micro instance and published on gh-pages:
https://schematics.github.io/schematics-benchmark/

**Comment by bintoro** [comment]
Hmm. Yeah, the parallel repo makes sense. Thanks for setting up the whole thing!

I suppose this can now be closed.

**Comment by lkraider** [comment]
Indeed. Also, feel free to contribute new benchmarks.

**Pull request closed without merging**
