### PR TITLE
Simplify PolyModelType.find_model for readability

### PR DESCRIPTION
**Pull request by kstrauser**
This rearranges existing logic to be more Python and readable. In particular, it removes a level of nested if's and uses multiple returns to avoid tracing a flag variable through the function.

My coworker asked me how this worked, and it took uncomfortably long for me to be able to tell him. This might shorten that awkward silence for the next person. :-)

### CODE REVIEW

**Comment by kstrauser** [comment]
I think this fixes #537, too.

**Comment by kstrauser** [comment]
@lkraider This is a pretty simple change that doesn't affect any client code. Think we could sneak this into the upcoming release?

**Comment by lkraider** [comment]
Thanks! I am organizing a 2.1 release, this will be in it!

**Comment by kstrauser** [comment]
Awesome, thanks!

**Pull request merged**
