### PR TITLE
Issue 279

### PR DESCRIPTION
**Pull request by kracekumar**
- Fix the circular import issue.

### CODE REVIEW

**Comment by bintoro** [comment]
Sooo this is interesting.

A few days ago, I noticed there was an import statement inside `FieldDescriptor.__set__()`, so I promptly moved it to the end of the file (https://github.com/schematics/schematics/commit/860d71778421981f284c0612aec665ebf0cfcba2). The reason is that calling `import` is expensive even if the module has already been loaded.

Then I found this PR, which is the exact reverse of the change I made.

I wonder why the reporter of #279 had run into a circular import because clearly it had worked for other people. @kracekumar do you have any idea of what went wrong there?

Let's try the bottom import again with v1.1.1. At least all tests are passing. If people start seeing the import issue again, then we'll figure it out, but IMO an import statement cannot live inside one of the most frequently called functions in the library.

**Comment by kracekumar** [comment]
@bintoro I didn't do poor introspection.

Sure. We can move that to bottom of the function. But imports are cached in `sys.modules` and on next run it will be fetched from `sys.modules` correct ? I agree with you to keep imports outside function definitions to avoid any run time issues.

**Comment by bintoro** [comment]
Yeah, imports are cached, but simply invoking the `import` statement nearly tripled the execution time of the setter method.

I just don't understand why that one guy ran into an import issue while the rest of us didn't.

Apparently I was the one who originally created the circular import in https://github.com/schematics/schematics/commit/03b2fd97fb47c00e8d667cc8ea7254cc64d0f0a0 when I needed to use `Model` in `compound.py`. I solved it by moving the import in `models.py` from the top to the bottom of the file, which was fine until for some reason it didn't work for the person who opened #279.

**Comment by bintoro** [comment]
@kracekumar I've got it. The circular import only occurred when `types.compound` was imported before the `models` module. The other way around it has always worked fine. I did the bottom import trick in `types/compound.py` as well, and now it's good both ways. :tada:

**Pull request merged**
