### PR TITLE
Add support for arbitrary field metadata.

### PR DESCRIPTION
**Pull request by chadrik**
Hi,
Here's a pull request for the metadata/annotations feature discussed in #333

It's dead simple.  I went with the name `metadata` instead of `annotations` because I think `metadata` is more self-explanatory, and I feel that `annotations` implies strings only.

### CODE REVIEW

**Comment by bintoro** [comment]
Looks pretty good to me! I have hesitations about the name `metadata`, though. Programs might have uses for the container that go beyond descriptive properties. A database column, for instance, is not really metadata IMO.

For reference, the import and export loops have a proprietary data bag called `app_data`, but I can't come up with anything useful following that precedent.

Applications using this feature are likely going to pass the argument to many, perhaps most, of their fields, so the shorter the better. Something that occurred to me is simply `ext` for extended or extension attributes. Pro: short; usage-agnostic; could be used elsewhere as well. Contra: usage not self-evident.

Any ideas? Basically the name should convey "custom attributes go here".

**Comment by chadrik** [comment]
I think `ext` is a bit too cryptic.  Here are some other ideas that meet the brevity requirement:

- `attrs`:  it's actually a dictionary, so maybe misleading?
- `data`: pretty generic, but then again, so is its purpose
- `extra`: my favorite

and one more inspired by `ext` but a bit more explicit:
- `external`

**Comment by bintoro** [comment]
Mm-hmm. I tried to push for `attrs` in #333. Now I'm thinking it's too vague because nothing indicates it's for proprietary attributes. The same goes for `data`.

I'm surprised to hear `ext` seems cryptic; I thought it was pretty standard for "extension", "extended", etc. But `extra` is definitely a good alternative. Anyone else want to chime in?

In #333, I envisioned that the extras would be exposed as attributes on the container object: `somefield.extra.description`. (This is similar to the `context` object present during import/export.) What are your thoughts on this?

**Comment by chadrik** [comment]
> I'm surprised to hear `ext` seems cryptic; I thought it was pretty standard for "extension", "extended", etc. 

It's growing on me a little bit, but I still prefer more explicit names.

> In #333, I envisioned that the extras would be exposed as attributes on the container object: `somefield.extra.description`. (This is similar to the context object present during import/export.) What are your thoughts on this?

I'm concerned that this introduces all of the issues regarding name clashes and dictionary methods that we've talked about in #375.  It seems acceptable and even intuitive to me that a container that holds *custom, external* data is left completely as-is, but I also see the appeal of attr-based access.

Consider this.  Stylistically a lot of people will probably prefer to declare their extra data like this:

```python
class Person(Model):
    first_name = StringType(
        required=True,
        extra=dict(
            title='First Name',
            description="The person's first name")
        )
    age = IntType(
        extra=dict(
            description="The person's age",
            as_sql_col='NUMBER')
        )
```

So, I think a simple solution is for schematics to provide an attr-dict util class that users can use if they like:

```python
class Person(Model):
    first_name = StringType(
        required=True,
        extra=AttrDict(
            title='First Name',
            description="The person's first name")
        )
    age = IntType(
        extra=AttrDict(
            description="The person's age",
            as_sql_col='NUMBER')
        )
```

I've also been thinking about your concerns about the term `metadata`.  I could be wrong, but I don't think that most developers feel strongly that metadata must be purely descriptive.  What we're talking about is data related to other data (the field), and I don't think that someone who wants to associate a sql column with a `schematics` field will be confused or discouraged when they spot "metadata" in the code or docs.  Also, not that it's a strong argument, but "metadata" is the term that [`marshmallow`](https://marshmallow.readthedocs.org/en/latest/) uses for the same purpose.

My 2 c.  I'll take a poll of the devs here at work to see what they think.

**Comment by chadrik** [comment]
In case it helps the four devs that I forwarded this discussion to voted for `metadata`.

**Comment by nrusch** [comment]
I'm one of the developers @chadrik mentioned, and I just wanted to add my voice in support of this, and more specifically, in favor of the `metadata` keyword.

Within development circles, the concept of "metadata" is pretty universally understood at this point, and I think the value of a keyword that is effectively self-documenting outweighs any of the potential advantages of choosing a shorter alternative.

> Programs might have uses for the container that go beyond descriptive properties. A database column, for instance, is not really metadata IMO.

The only thing "metadata" really says is that its contents have no direct impact on the functionality of the entity it is attached to. Whether those contents affect the functionality of a containing **program** is irrelevant. A database column, for instance, is absolutely metadata.

Thanks.

**Comment by bintoro** [comment]
Okay, you've convinced me.

One last question before I merge. Now that we've agreed on *metadata* in principle, do you guys also prefer `metadata` over just `meta`? I don't think the shortened variant ever came up, even though it's widely used as well. I'm fine with either.

**Comment by nrusch** [comment]
Personally, while I don't mind `meta`, I would say I prefer the specificity of `metadata`. Even at twice the character count, it's far from the longest keyword name for fields.

**Pull request merged**
