### PR TITLE
Added translation files to the distribution and German translations

### PR DESCRIPTION
**Pull request by hkage**
Hi there,

We are using `schematics` in a Django based project and intend to display the validation messages in multiple languages. Therefore I added a German translation catalogue for schematics and slightly modified the `setup.py` so that translation files (`pot`, `po` and `mo` files) are part of the source distribution.

For now I created the mo-files manually with Babel and modified the `MANIFEST.in` file to include the translations. This workflow could be improved by adding `babel` to a development requirements file and extending the `sdist` command to also execute `python setup.py compile_catalog` so that mo-files are generated automatically. But I didn't want to change that without a first feedback of you concerning this pull request.

Best regards

### CODE REVIEW

**Review by lkraider — APPROVED** [review]
Looks good to me!

**Comment by hkage** [comment]
Thanks for taking a look into the pull request. Do you plan a release of schematics, that might contain the translations files?

**Comment by hkage** [comment]
Hi there,

we are planning an internal release of our Django project that relies heavily on schematics in the next weeks and we are going to present it to our German customer. Is there a chance to get this pull request merged and maybe a new release of schematics containing the translation files? Or are no release planned by you until then?

Otherwise we would create a pre-release from the fork we created and upload it to our private devpi server until then.

Thanks in advance!

**Comment by hkage** [comment]
The pull request contained an internal version suffix we used to upload a pre-release within our own devpi server. I removed the version suffix, so that it matches the current version again.

**Comment by hkage** [comment]
Thanks for merging the changes :+1:

**Pull request merged**
