### PR TITLE
Improve the documentation of get_mock_object

### PR DESCRIPTION
**Pull request by charlax**

### CODE REVIEW

**Comment by j2labs** [comment]
If we can push this into the master branch, I will include these doc
changes when I push 1.0.1 later tonight.

Krace, thoughts?

On Wed, Feb 4, 2015 at 4:23 PM, Charles-Axel Dein <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/schematics/schematics/pull/276
> Commit Summary
>
>    - Improve the documentation of get_mock_object
>
> File Changes
>
>    - *M* docs/community.rst
>    <https://github.com/schematics/schematics/pull/276/files#diff-0> (6)
>    - *M* docs/development.rst
>    <https://github.com/schematics/schematics/pull/276/files#diff-1> (24)
>    - *M* docs/install.rst
>    <https://github.com/schematics/schematics/pull/276/files#diff-2> (6)
>    - *M* schematics/models.py
>    <https://github.com/schematics/schematics/pull/276/files#diff-3> (7)
>
> Patch Links:
>
>    - https://github.com/schematics/schematics/pull/276.patch
>    - https://github.com/schematics/schematics/pull/276.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/276>.
>



-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by charlax** [comment]
You want me to do the PR for the master branch? Or is it ok as is?

**Comment by jmsdnns** [comment]
It's up to Krace, imo. Or one of the other commiters.

On Wednesday, February 4, 2015, Charles-Axel Dein <notifications@github.com>
wrote:

> You want me to do the PR for the master branch? Or is it ok as is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/276#issuecomment-72967873>.
>


-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by kracekumar** [comment]
No worries, I updated the other pull.

**Pull request merged**
