### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by bintoro**
* [Bug] befa202 Fix Unicode issue with DecimalType
* [Documentation] 41157a1 Documentation overhaul
* [Bug] 860d717 Fix import that was negatively affecting performance
* [Feature] 93b554f Add DataObject to datastructures.py
* [Bug] #236 Set `None` on a field that's a compound type should honour that semantics
* [Maintenance] #348 Update requirements
* [Maintenance] #346 Combining Requirements
* [Maintenance] #342 Remove to_primitive() method from compound types
* [Bug] #339 Basic number validation
* [Bug] #336 Don't evaluate serializable when accessed through class
* [Bug] #321 Do not compile regex
* [Maintenance] #319 Remove mock from install_requires

### CODE REVIEW

**Comment by j2labs** [comment]
Aww yiss!!

Great work!!

On Tuesday, November 3, 2015, Kalle Tuure <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/schematics/schematics/pull/353
> Commit Summary
>
>    - Remove mock from install_requires
>    - Removed the doc section about the project's fork.
>    - Merge pull request #320 from jmsdnns/development
>    - Merge pull request #319 from breerly/patch-2
>    - Do not compile regex
>    - Merge pull request #321 from xealot/deepcopy
>    - Don't evaluate serializable when accessed through class
>    - Fixed `NumberType` so it actually checks if its value is a number
>    - Added test to cover number validation
>    - Merge pull request #339 from jmsdnns/jmsdnns-basic-number-validation
>    - Merge pull request #336 from bintoro/access-serializable
>    - Remove to_primitive method from compound types.
>    - Merge pull request #342 from wraziens/compound_to_primitive
>    - Merge branch 'master' into development
>    - combining requirements files
>    - Merge pull request #346 from arosenfeld/requirements
>    - Update requirements
>    - Merge branch 'master' into development
>    - Add DataObject to datastructures.py
>    - Move import
>    - Documentation overhaul
>    - Merge pull request #348 from bintoro/requirements
>    - Update changelog
>
> File Changes
>
>    - *M* HISTORY.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-0> (27)
>    - *M* MANIFEST.in
>    <https://github.com/schematics/schematics/pull/353/files#diff-1> (2)
>    - *M* README.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-2> (38)
>    - *D* dev-requirements.txt
>    <https://github.com/schematics/schematics/pull/353/files#diff-3> (2)
>    - *D* docs/_themes/LICENSE
>    <https://github.com/schematics/schematics/pull/353/files#diff-4> (45)
>    - *D* docs/_themes/README.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-5> (25)
>    - *D* docs/_themes/flask_theme_support.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-6> (86)
>    - *D* docs/_themes/kr_small/layout.html
>    <https://github.com/schematics/schematics/pull/353/files#diff-7> (22)
>    - *D* docs/_themes/kr_small/static/flasky.css_t
>    <https://github.com/schematics/schematics/pull/353/files#diff-8> (294)
>    - *D* docs/_themes/kr_small/theme.conf
>    <https://github.com/schematics/schematics/pull/353/files#diff-9> (10)
>    - *M* docs/api/contrib.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-10> (1)
>    - *M* docs/api/models.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-11> (3)
>    - *M* docs/api/transforms.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-12> (3)
>    - *M* docs/api/types.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-13> (3)
>    - *M* docs/api/validation.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-14> (3)
>    - *A* docs/basics/install.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-15> (46)
>    - *R* docs/basics/quickstart.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-16> (0)
>    - *M* docs/conf.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-17> (21)
>    - *R* docs/development/community.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-18> (7)
>    - *R* docs/development/development.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-19> (22)
>    - *M* docs/index.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-20>
>    (153)
>    - *D* docs/install.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-21> (47)
>    - *D* docs/toc.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-22> (46)
>    - *M* docs/usage/exporting.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-23> (4)
>    - *M* docs/usage/importing.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-24> (2)
>    - *M* docs/usage/models.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-25> (2)
>    - *M* docs/usage/types.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-26> (2)
>    - *M* docs/usage/validation.rst
>    <https://github.com/schematics/schematics/pull/353/files#diff-27> (4)
>    - *D* requirements-testing.txt
>    <https://github.com/schematics/schematics/pull/353/files#diff-28> (8)
>    - *A* requirements.txt
>    <https://github.com/schematics/schematics/pull/353/files#diff-29> (8)
>    - *M* schematics/datastructures.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-30>
>    (114)
>    - *M* schematics/models.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-31> (4)
>    - *M* schematics/types/base.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-32> (11)
>    - *M* schematics/types/compound.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-33> (20)
>    - *M* schematics/types/serializable.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-34> (5)
>    - *M* setup.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-35> (3)
>    - *M* tests/test_flatten.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-36> (6)
>    - *M* tests/test_types.py
>    <https://github.com/schematics/schematics/pull/353/files#diff-37> (6)
>    - *M* tox.ini
>    <https://github.com/schematics/schematics/pull/353/files#diff-38> (2)
>
> Patch Links:
>
>    - https://github.com/schematics/schematics/pull/353.patch
>    - https://github.com/schematics/schematics/pull/353.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/353>.
>


-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>

**Comment by kracekumar** [comment]
:+1:

**Comment by edc** [comment]
:clap: Would this be pushed to PyPI automatically?

**Comment by kracekumar** [comment]
No, someone has to do it manually by running appropriate setup.py command.

On Tue, Nov 3, 2015 at 11:35 PM, Eddie Cao <notifications@github.com> wrote:

> [image: :clap:] Would this be pushed to PyPI automatically?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/353#issuecomment-153438907>
> .
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Comment by bintoro** [comment]
Speaking of PyPI, the project description there hasn't been updated to reflect https://github.com/schematics/schematics/commit/7bcd9118ed80e1e8184b78567125e7a875a2c06d.

**Comment by bintoro** [comment]
@jmsdnns @kracekumar Would either of you mind uploading the [release](https://github.com/schematics/schematics/releases/tag/v1.1.1) to PyPI? Or I can do it as well if someone designates my PyPI account as a package owner.

**Comment by kracekumar** [comment]
User `bintoro` is now owner.

On Thu, Nov 5, 2015 at 1:35 AM, Kalle Tuure <notifications@github.com>
wrote:

> @jmsdnns <https://github.com/jmsdnns> @kracekumar
> <https://github.com/kracekumar> Would either of you mind uploading the
> release <https://github.com/schematics/schematics/releases/tag/v1.1.1> to
> PyPI? Or I can do it as well if someone designates my PyPI account as a
> package owner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/pull/353#issuecomment-153847773>
> .
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Pull request merged**
